### ISSUE TITLE
Support Easee Wallbox?

### ISSUE THREAD

**Issue by Nastras** [valiquette/homebridge-my-wallbox#1]
Hello, I myself have as wallbox two Easee Home.

https://easee.com/
https://developer.easee.cloud/docs/web-api-overview

The company Easee has an open API with which you can control the wallboxes. Only every 24 hours a logon token must be renewed.

 I am also looking for a plugin for some time. But so far I could not find one. Unfortunately, I lack the knowledge to code the plugin myself.

Therefore, my question to you if you are interested in extending your plugin for the Easee wallbox.

If so, I would like to support you?

**Comment by valiquette** [comment]
Questions
What functionality are you looking for? The same lock/unlock capability or something more?
I do not think it would be very difficult to swap the Wallbox APIs for  Easee’s But i don’t know how I would test them. Without access to an account. It might mean you would have to provide a lot of feedback in the process.

**Comment by Nastras** [comment]
Thanks for the quick reply! Glad to hear that it would be possible to support the Easee.

The start load and stop charging function of the easee for your plugin would be really great. 
In the future if everything works out and you want we can implement more functions together?

I would be very happy to give quick and detailed feedback on testing as well.
You just have to tell me what to test and when.

Would that be ok for you?

**Comment by valiquette** [comment]
Let me send you something next week, I would just need feed back and probably debug logs. the only hard part that we may have to go back and forth on is understanding what the API responses look like.

**Comment by Nastras** [comment]
Right. Just let me know when you need something 😉

**Comment by Nastras** [comment]
I have summarized a few api data.
Do these help you?

(Easee Start)
 
 curl --request POST \
     --url https://api.easee.cloud/api/chargers/IDXXXX/commands/start_charging \
     --header 'Authorization: bearer TOKEN'
     
Response

{
  "device": "IDXXXXX",
  "commandId": 25,
  "ticks": 6378024xxxxxxxx
}


(Easee Stop)

curl --request POST \
     --url https://api.easee.cloud/api/chargers/IDXXXXX/commands/stop_charging \
     --header 'Authorization: bearer TOKEN'
     
Response

{
  "device": "IDXXXXX",
  "commandId": 26,
  "ticks": 637802xxxxxxxxx
}

**Comment by Nastras** [comment]
![AC33B431-1F4A-4B57-B99A-23D4FF5B51EA](https://user-images.githubusercontent.com/27686185/153702925-6b77beff-e23d-4ddb-96d7-5146b9096b5e.jpeg)
![79080AE1-0AA3-4CBC-BC1A-8139E6935BFA](https://user-images.githubusercontent.com/27686185/153702929-d8fa4f82-0474-473d-a749-aefd78b1b703.jpeg)
![26AC9AFB-CAA1-430C-BFB2-0D02AF926D70](https://user-images.githubusercontent.com/27686185/153702931-d80db5cf-9734-449f-bfbf-ac8e5d943a43.jpeg)

**Comment by valiquette** [comment]
Moving this issue to https://github.com/valiquette/homebridge-easee
