### ISSUE TITLE
12K requests per minute to Wallbox API sign in endpoint

### ISSUE THREAD

**Issue by AlbertMorenoDEV** [valiquette/homebridge-my-wallbox#12]
Hello!

I've noticed it's getting stuck in some cases doing up to 12K rpm to the sign-in endpoint. Not sure if it's related to the retry logic.

Thank you

**Comment by valiquette** [comment]
Version 1.1.1 should have corrected issues with a request storm. The API response had the TTL reduced to just 15 min. The lates versions skips any refresh and just signs in when needed. Which should be when a HomeKit get happens, such as opening HomeKit or refreshing the homebridge accessories page. If you have some other app in the mix it might behave unexpectedly. I will need to see if there are any other changes in the API responses.

**Comment by AlbertMorenoDEV** [comment]
awesome! thank you

**Comment by valiquette** [comment]
I assume you have not seen this again, the response for the token TTL has changed again to now 24hours.
