### ISSUE TITLE
cant start my wallbox charger

### ISSUE THREAD

**Issue by bucofski** [valiquette/homebridge-my-wallbox#22]
Hey,

Since the update to 1.1.20 I can't start my wallbox to charge the car. If I unlock my wallbox I see that in the logs but when I press start I don't see anything in the logs and the button does toggle ON/OFF.
Can I do something to help find the issue?

Kind regards

**Comment by valiquette** [comment]
I could reproduce it. v1.1.21 should correct this.
please let me know.

**Comment by bucofski** [comment]
I already test the new version and it worked perfectly. THX for the quick fix! Just to let you know i use a walbox copper SB so it does work on other types from walbox!
