### ISSUE TITLE
Unknown device message received: undefined

### ISSUE THREAD

**Issue by pasaone** [valiquette/homebridge-my-wallbox#5]
Hello,

The plugin works perfectly for me but I still have in the logs the message:
[Wallbox] Unknown device message received: undefined
Is it normal or not as it comes often?

Thanks

**Comment by valiquette** [comment]
That error is benign, but there is potential for homekit lock status to get out of sync, it is really a status for being locked and you will see it as often as you refresh when locked. The API is inconsistent with how it response and I have changed the way I handle these updates, but have not had the ability to test everything I would like to. I could publish the fix as a beta for you if want to try this for a complete charging session.

**Comment by valiquette** [comment]
I did publish 1.0.8-beta

**Comment by valiquette** [comment]
corrected in 1.0.8 thanks for reporting this.

**Comment by sndrod** [comment]
> Hello,
> 
> The plugin works perfectly for me but I still have in the logs the message: [Wallbox] Unknown device message received: undefined Is it normal or not as it comes often?
> 
> Thanks

Hi Pasaone, my question actually relates to the issue you had with Netatmo in August last year, but that ticket is closed. I have a near identical issue as outlined here.  https://github.com/home-assistant/core/issues/120292

Did you manage to resolve your issue, and if so, how?

Many thanks for any help you can offer
