### ISSUE TITLE
Undefined error 

### ISSUE THREAD

**Issue by Stan-loo** [valiquette/homebridge-my-wallbox#8]
Hi,

I have issues with this error I updated Node.js to v16. After the update the system just boot looped. The only thing what worked was deleting the whole Npm.

Wat is required to use the newer version of Node.js or what can stop this from happening.

Thanks for the help.

Log 1 is with the old Node.js
Log 2 is with the new Node.js

Log 1 :
node:30661) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-my-wallbox/wallboxplatform.js:258:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30661) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)

Log 2 :
TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at /usr/local/lib/node_modules/homebridge-my-wallbox/wallboxplatform.js:258:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[20/06/2022, 16:09:16] Got SIGTERM, shutting down Homebridge...

**Comment by valiquette** [comment]
Quick question, what specific versions of node.js are old and new?  Not that it matter as I can see from what you have provided what the issue is and I will get a fix out later today. 
In the mean time I believe if you enable show charger control, and choose to show as a thermostat you will avoid this error.

**Comment by Stan-loo** [comment]
Old version is v12.19.0
Newest version v16.15.1

But I switched to the old version (v12.19.0) as this is the only version what prevents a boot loop.

**Comment by valiquette** [comment]
v1.0.10 should address the issue reported.
Thanks
