### ISSUE TITLE
Pause/Resume charging

### ISSUE THREAD

**Issue by digidolphin** [valiquette/homebridge-my-wallbox#9]
It would be brilliant, if there was a pause/resume option for the charger, allowing you to fully control (and automate) when and how to charge. Thanks.

**Comment by valiquette** [comment]
Have you looked at the settings and tried the various charger control options? I experimented a little bit with this. The show simple start/stop should be the same as pause resume. 
none will show just the lock/unlock
simple start/spot will show lock and switch for charging
start/stop with amps will show lock and light bulb which off is stop and any % is on at those amps
full uses a thermostat to interact, closest I could get to the native app
I think you could build automation around these. But let me know what exactly you are looking for if this does not work for you.

**Comment by digidolphin** [comment]
Thanks. I also found an option 4 that gives you a combo of 2 and 3. But
regardless of which one I choose and try out, it doesn't actually
pause/resume. I can unlock fine, so there is some kind of connection, but I
cannot pause a charge (or change amps)

**Comment by valiquette** [comment]
I am looking into this and see if I can improve it a bit, I am not sure it works unless there is a car connected.
stay tuned.

**Comment by digidolphin** [comment]
Thanks. To clarify: I tested while my car was connected and charging,
hoping that I could pause it.

**Comment by valiquette** [comment]
I found a bug that is failing any remote action, I fix that, but will not be able to test myself until the weekend

**Comment by valiquette** [comment]
I publish a beta version that you can try, it should address the bug with pause.

**Comment by digidolphin** [comment]
I tried it, but it keeps saying 'Unable to start/stop at this time'. I've
tried both when it is locked and unlocked. I can start and stop through the
Wallbox' own web-interface.

**Comment by valiquette** [comment]
for now that error should only show up when locked and it does not send the command, if unlocked and sent it would be a different message.

**Comment by digidolphin** [comment]
I am getting the same error when unlocked:
[25/08/2022, 16:42:18] [Wallbox2] Unlocking PulsarPlus SN 462106
[25/08/2022, 16:42:31] [Wallbox2] Charging time for 100% charge  03:23:07
[25/08/2022, 16:42:31] [Wallbox2] Unable to start/stop at this time

**Comment by valiquette** [comment]
any chance you could enable debug and send the debug log for that ?

**Comment by valiquette** [comment]
Try Beta 3, I have verified it works in my environment. The API response change somewhere along the way and made some major tweaks to how it will update and stay sync'd. I am not sure how it would work with the automation you are considering. Let me know.

**Comment by digidolphin** [comment]
Great job! It works for me as well. Only thing is it will ask me to unlock
before I can start/stop. In the web/app interface for wallbox I do not need
to do that, so perhaps it can be tweaked a bit more. Nevertheless it works
for my needs now.

**Comment by valiquette** [comment]
I thought I was mirroring the app's behavior, I swear it prompts me to unlock prior, but if I have that wrong I'll change it. This is why I was curious about automation perhaps needing 2 steps. I could auto unlock or skip the check. Anyhow I will take another look.

**Comment by valiquette** [comment]
V1.0.14 should be mirroring the app at this point. 
The charger does need to be unlocked when first connected, but not if it re locks with a car still connected.

**Comment by digidolphin** [comment]
I have no idea how to do that or how to get the logs out of my raspberry
pi, but will gladly help if you can tell me how.

**Comment by valiquette** [comment]
in the homebridge UI there are 3 dots I the upper right hand corner. Click and select home bridge settings then toggle Homebridge Debug Mode  to on. 
Restart, when if boots up go back to the same corner and select the first button for Logs, then there will be be 2 other buttons a download and delete.
delete (truncate) the current log so things are clean, restart just this plugin, then replicate the issue you have. 
When your set go back to the top right and download the log, 
you can attach the log here.

Last you can go back and turn the debug logging off
